### ISSUE TITLE
Renaming uses script path rather than target directory

### ISSUE THREAD

**Issue by Cyber5imon** [sinedied/movie-renamer#1]
Notice from this output the error when renaming the files:

C:\Users\Simon>movie-renamer F:\private\rtorrent\Send\movies
Listing files...
Scraping IMDB results...
?   The.Bourne.Legacy.2012.2160p.BluRay.REMUX.HEVC.DTS-X.7.1-FGT.mkv
?   The.Bourne.Legacy.2012.2160p.BluRay.REMUX.HEVC.DTS-X.7.1-FGT.mkv
 -> The Bourne Legacy (2012).mkv: Yes
?   The.Bourne.Ultimatum.2007.2160p.BluRay.REMUX.HEVC.DTS-X.7.1-FGT.mkv
?   The.Bourne.Ultimatum.2007.2160p.BluRay.REMUX.HEVC.DTS-X.7.1-FGT.mkv
 -> The Bourne Ultimatum (2007).mkv: Yes
?   The.Bourne.Supremacy.2004.2160p.BluRay.REMUX.HEVC.DTS-X.7.1-FGT.mkv
?   The.Bourne.Supremacy.2004.2160p.BluRay.REMUX.HEVC.DTS-X.7.1-FGT.mkv
 -> The Bourne Supremacy (2004).mkv: Yes
Renaming files...
Done!
Error while renaming "The.Bourne.Legacy.2012.2160p.BluRay.REMUX.HEVC.DTS-X.7.1-FGT.mkv": Error: ENOENT: no such file or directory, rename 'C:\Users\Simon\The.Bourne.Legacy.2012.2160p.BluRay.REMUX.HEVC.DTS-X.7.1-FGT.mkv' -> 'C:\Users\Simon\The Bourne Legacy (2012).mkv'
Error while renaming "The.Bourne.Ultimatum.2007.2160p.BluRay.REMUX.HEVC.DTS-X.7.1-FGT.mkv": Error: ENOENT: no such file or directory, rename 'C:\Users\Simon\The.Bourne.Ultimatum.2007.2160p.BluRay.REMUX.HEVC.DTS-X.7.1-FGT.mkv' -> 'C:\Users\Simon\The Bourne Ultimatum (2007).mkv'
Error while renaming "The.Bourne.Supremacy.2004.2160p.BluRay.REMUX.HEVC.DTS-X.7.1-FGT.mkv": Error: ENOENT: no such file or directory, rename 'C:\Users\Simon\The.Bourne.Supremacy.2004.2160p.BluRay.REMUX.HEVC.DTS-X.7.1-FGT.mkv' -> 'C:\Users\Simon\The Bourne Supremacy (2004).mkv'

**Comment by Cyber5imon** [comment]
I've fixed the code and added some more functionality, but I am unable to upload the new branch and create a pull request...

**Comment by sinedied** [comment]
@SPDurkee you need to fork the repo on your account so that you can propose a PR

**Comment by Cyber5imon** [comment]
This is my first time using GitHub. I believe I have successfully created the pull request with the code changes…

--
Take Care,
Simon Durkee

This email message is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution of this email is prohibited. If you are not the intended recipient, please contact the sender and destroy all paper and electronic copies of this message.
